/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#324863",
        "champagne-highlight": "#FFF9F0",
        "on-tertiary-fixed-variant": "#604100",
        "on-primary-container": "#8ea4c3",
        "secondary-fixed-dim": "#ffb783",
        "surface-container-high": "#eee7dd",
        "tertiary": "#322000",
        "on-secondary-fixed-variant": "#713700",
        "on-primary": "#ffffff",
        "deep-midnight": "#0A0F14",
        "secondary-container": "#fc8f34",
        "surface-bright": "#fff8f0",
        "on-secondary-container": "#663100",
        "surface-container-low": "#faf3e9",
        "on-surface-variant": "#43474d",
        "outline": "#74777e",
        "tertiary-container": "#4e3400",
        "inverse-on-surface": "#f7f0e6",
        "error-container": "#ffdad6",
        "primary": "#0c243d",
        "sunset-orange": "#E67E22",
        "tertiary-fixed": "#ffdeae",
        "on-tertiary-container": "#d09937",
        "warm-sand": "#F9F2E8",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#031c35",
        "tertiary-fixed-dim": "#f8bc57",
        "surface-dim": "#e0d9cf",
        "primary-fixed-dim": "#b2c8e8",
        "on-surface": "#1e1b15",
        "primary-container": "#243a54",
        "surface-variant": "#e8e2d8",
        "outline-variant": "#c4c6ce",
        "on-error-container": "#93000a",
        "surface": "#fff8f0",
        "on-secondary-fixed": "#301400",
        "azure-blue": "#243A54",
        "slate-text": "#1A1A1A",
        "inverse-primary": "#b2c8e8",
        "surface-container": "#f4ede3",
        "secondary-fixed": "#ffdcc5",
        "inverse-surface": "#33302a",
        "on-background": "#1e1b15",
        "on-error": "#ffffff",
        "primary-fixed": "#d2e4ff",
        "surface-tint": "#4a607c",
        "background": "#fff8f0",
        "surface-container-highest": "#e8e2d8",
        "on-tertiary-fixed": "#281900",
        "secondary": "#944a00",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-lg": ["Playfair Display"],
        "headline-xl": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Inter"],
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-md": "24px",
        "unit": "4px",
        "stack-lg": "48px",
        "gutter": "16px",
        "stack-sm": "8px",
      },
    },
  },
  plugins: [],
};
